apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: spring-sensors-cloud
  labels:
    apps.tanzu.vmware.com/workload-type: cloud
    app.kubernetes.io/part-of: spring-sensors-cloud
spec:
  params:
    - name: infra-id
      value: spring-sensors-cloud
    - name: region
      value: us-west-2
    - name: engineVersion
      value: "3.9.13" 
  source:
    git:
      url: https://github.com/garreeoke/spring-sensors-rabbit.git
      ref:
        branch: main
  serviceClaims:
    - name: broker
      ref:
        apiVersion: services.apps.tanzu.vmware.com/v1alpha1
        kind: ResourceClaim
        name: spring-sensors-cloud